### PR TITLE
Create Italian Translation  it_IT

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by mokurin000** [comment]
hi! thanks for your translation, could you please place `waylyrics.po` at `locales/it_IT/LC_MESSAGES` ? This will make it installed automaticallt by current packging scripts

**Comment by albanobattistella** [comment]
> hi! thanks for your translation, could you please place `waylyrics.po` at `locales/it_IT/LC_MESSAGES` ? This will make it installed automaticallt by current packging scripts

Hi,
I tried to create folder..but I can't..I don't know why.

**Comment by mokurin000** [comment]
> > hi! thanks for your translation, could you please place `waylyrics.po` at `locales/it_IT/LC_MESSAGES` ? This will make it installed automaticallt by current packging scripts
> 
> Hi, I tried to create folder..but I can't..I don't know why.

ok... May I push directly to your branch after I back home? or try `mkdir -p ...` first

**Comment by xmb505** [comment]
You're so good, love form China. :)

**Pull request merged**
